version: '3.8'

services:
  api:
    build: ./api
    ports:
      - "5000:5000"

  generator:
    build: ./generator
    depends_on:
      - api
  can-reader:
    build: ./can_reader
    network_mode: host      # Krävs för att komma åt vcan0 på värdmaskinen
    depends_on:
      - api
